import java.util.*;

/*
// Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

class Q2 {
    public static void main(String[] args) {
        System.out.println(fibEvenSum());
    }

    private static int fibEvenSum() {
        ArrayList<Integer> arr = new ArrayList<Integer>();
        arr.add(1);
        arr.add(2);
        int sum = 2;
        
        while(arr.get(arr.size() - 1) < 4000000) {
            arr.add(arr.get(arr.size() - 2) + arr.get(arr.size() - 1));

            if (arr.get(arr.size() - 1) % 2 == 0) {
                sum += arr.get(arr.size() - 1);
            }
        }
        return sum;
    }
}




